/**
 * HS code index access.
 *
 * hs-index.json holds every 6-digit product line under the chapters our
 * taxonomy references, generated by scripts/build-hs-index.mjs. Segments
 * declare coarse prefixes ("04", "1806"); the drill-down expands those to the
 * individual product lines beneath them.
 */

import indexJson from "./hs-index.json";

const HS_INDEX = indexJson as Record<string, string>;

export function describe(code: string): string {
  return HS_INDEX[code] ?? `HS ${code}`;
}

export const HS_DESCRIPTIONS = HS_INDEX;

/**
 * Expand segment prefixes into the 6-digit lines beneath them.
 *
 * Ordered by chapter breadth so that when a segment spans more product lines
 * than we can query, the truncation falls on the narrowest, least significant
 * chapters rather than an arbitrary slice.
 */
export function expandToProductCodes(prefixes: string[]): string[] {
  const byPrefix = new Map<string, string[]>();

  for (const prefix of prefixes) {
    const matches: string[] = [];
    for (const code of Object.keys(HS_INDEX)) {
      if (code.startsWith(prefix)) matches.push(code);
    }
    if (matches.length > 0) byPrefix.set(prefix, matches.sort());
  }

  return Array.from(byPrefix.values())
    .sort((a, b) => b.length - a.length)
    .flat();
}
