/**
 * Sector taxonomy for the opportunity engine.
 *
 * Every segment carries structural economics that the scoring engine reads.
 * These are not decorative labels: `capitalIntensity`, `regulatoryBurden` and
 * friends feed directly into the feasibility term, and `hsCodes` are what the
 * trade connector uses to measure how much of a country's demand is currently
 * being satisfied by imports.
 *
 * All 0..1 fields are normalised so the engine never has to know sector units.
 */

export interface Segment {
  id: string;
  name: string;
  /** What the business actually is, in one line. */
  description: string;
  /**
   * Harmonised System codes for the physical goods this segment trades.
   * Empty for pure-service segments, which fall back to demand modelling
   * because services largely do not show up in customs data.
   */
  hsCodes: string[];
  /** 0 = bootstrappable from a laptop, 1 = needs a financed industrial plant. */
  capitalIntensity: number;
  /** 0 = start tomorrow, 1 = licences, inspections, national regulator. */
  regulatoryBurden: number;
  /** 0 = works with unreliable power/roads, 1 = needs grid, port or cold chain. */
  infrastructureDependency: number;
  /** 0 = cannot realistically be produced locally, 1 = highly localisable. */
  importSubstitutability: number;
  /** Realistic months from capital deployed to first revenue. */
  timeToRevenueMonths: number;
  /** 0 = automated, 1 = people-heavy. Matters where labour is cheap or scarce. */
  laborIntensity: number;
  /** <1 = staple, demand survives downturns. >1 = discretionary, cyclical. */
  incomeElasticity: number;
  /** True if the customer is a business rather than a household. */
  b2b: boolean;
}

export interface Sector {
  id: string;
  name: string;
  icon: string;
  blurb: string;
  /**
   * World Bank value-added indicator that best proxies *domestic supply*
   * for this sector. Null where no national accounts line matches, in which
   * case the engine leans on trade and demography instead.
   */
  supplyIndicator: string | null;
  /** Typical share of an economy this sector captures. Used to size demand. */
  gdpShareBaseline: number;
  segments: Segment[];
}

export const SECTORS: Sector[] = [
  {
    id: "fnb",
    name: "Food & Beverage",
    icon: "🍽️",
    blurb:
      "Everything from primary food processing to restaurants. Usually the fastest sector to show an import-substitution gap because food is consumed continuously and customs data is granular.",
    supplyIndicator: "NV.AGR.TOTL.ZS",
    gdpShareBaseline: 0.11,
    segments: [
      {
        id: "fnb-processing",
        name: "Packaged Food Processing",
        description:
          "Turning local raw agricultural output into shelf-stable packaged product.",
        hsCodes: ["16", "19", "20", "21"],
        capitalIntensity: 0.55,
        regulatoryBurden: 0.6,
        infrastructureDependency: 0.65,
        importSubstitutability: 0.85,
        timeToRevenueMonths: 12,
        laborIntensity: 0.5,
        incomeElasticity: 0.7,
        b2b: true,
      },
      {
        id: "fnb-dairy",
        name: "Dairy & Chilled",
        description:
          "Milk, cheese, yoghurt and chilled goods requiring an unbroken cold chain.",
        hsCodes: ["04"],
        capitalIntensity: 0.7,
        regulatoryBurden: 0.7,
        infrastructureDependency: 0.9,
        importSubstitutability: 0.8,
        timeToRevenueMonths: 14,
        laborIntensity: 0.45,
        incomeElasticity: 0.6,
        b2b: true,
      },
      {
        id: "fnb-bakery",
        name: "Bakery & Confectionery",
        description:
          "Bread, pastry and sugar confectionery, typically serving a tight local radius.",
        hsCodes: ["17", "1806", "1905"],
        capitalIntensity: 0.3,
        regulatoryBurden: 0.4,
        infrastructureDependency: 0.5,
        importSubstitutability: 0.9,
        timeToRevenueMonths: 5,
        laborIntensity: 0.75,
        incomeElasticity: 0.8,
        b2b: false,
      },
      {
        id: "fnb-beverage",
        name: "Beverages & Bottling",
        description:
          "Soft drinks, juice, water bottling and alcohol production.",
        hsCodes: ["22"],
        capitalIntensity: 0.65,
        regulatoryBurden: 0.65,
        infrastructureDependency: 0.75,
        importSubstitutability: 0.85,
        timeToRevenueMonths: 12,
        laborIntensity: 0.35,
        incomeElasticity: 0.9,
        b2b: true,
      },
      {
        id: "fnb-restaurants",
        name: "Restaurants & QSR",
        description:
          "Dine-in, quick service and delivery-first kitchen formats.",
        hsCodes: [],
        capitalIntensity: 0.4,
        regulatoryBurden: 0.45,
        infrastructureDependency: 0.55,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 6,
        laborIntensity: 0.9,
        incomeElasticity: 1.4,
        b2b: false,
      },
      {
        id: "fnb-specialty-export",
        name: "Specialty Food Export",
        description:
          "High-margin origin products (olive oil, spices, preserves) sold into diaspora and premium export markets.",
        hsCodes: ["1509", "0904", "2005", "2008"],
        capitalIntensity: 0.35,
        regulatoryBurden: 0.55,
        infrastructureDependency: 0.5,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 8,
        laborIntensity: 0.6,
        incomeElasticity: 1.2,
        b2b: true,
      },
    ],
  },
  {
    id: "agriculture",
    name: "Agriculture & Agritech",
    icon: "🌾",
    blurb:
      "Primary production and the technology layer above it. Strong signal where a country imports staples it has the climate to grow.",
    supplyIndicator: "NV.AGR.TOTL.ZS",
    gdpShareBaseline: 0.06,
    segments: [
      {
        id: "agri-protected",
        name: "Protected & Greenhouse Cultivation",
        description:
          "Controlled-environment growing that decouples yield from weather and extends season.",
        hsCodes: ["07", "0810"],
        capitalIntensity: 0.6,
        regulatoryBurden: 0.3,
        infrastructureDependency: 0.7,
        importSubstitutability: 0.9,
        timeToRevenueMonths: 10,
        laborIntensity: 0.7,
        incomeElasticity: 0.5,
        b2b: true,
      },
      {
        id: "agri-poultry-livestock",
        name: "Poultry & Livestock",
        description: "Meat, eggs and animal protein production at commercial scale.",
        hsCodes: ["01", "02", "0407"],
        capitalIntensity: 0.65,
        regulatoryBurden: 0.65,
        infrastructureDependency: 0.75,
        importSubstitutability: 0.85,
        timeToRevenueMonths: 12,
        laborIntensity: 0.6,
        incomeElasticity: 0.7,
        b2b: true,
      },
      {
        id: "agri-inputs",
        name: "Agricultural Inputs",
        description:
          "Fertiliser, seed, feed and crop protection — usually imported, often localisable.",
        hsCodes: ["31", "1209", "2309", "3808"],
        capitalIntensity: 0.7,
        regulatoryBurden: 0.75,
        infrastructureDependency: 0.7,
        importSubstitutability: 0.6,
        timeToRevenueMonths: 18,
        laborIntensity: 0.35,
        incomeElasticity: 0.4,
        b2b: true,
      },
      {
        id: "agri-tech",
        name: "Agritech & Farm Software",
        description:
          "Irrigation control, yield monitoring, marketplace and traceability tooling for growers.",
        hsCodes: [],
        capitalIntensity: 0.2,
        regulatoryBurden: 0.2,
        infrastructureDependency: 0.35,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 9,
        laborIntensity: 0.4,
        incomeElasticity: 1.1,
        b2b: true,
      },
      {
        id: "agri-postharvest",
        name: "Post-Harvest & Cold Storage",
        description:
          "Sorting, grading, packing and refrigerated storage that stops produce spoiling before sale.",
        hsCodes: [],
        capitalIntensity: 0.7,
        regulatoryBurden: 0.4,
        infrastructureDependency: 0.95,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 12,
        laborIntensity: 0.5,
        incomeElasticity: 0.6,
        b2b: true,
      },
    ],
  },
  {
    id: "manufacturing",
    name: "Manufacturing & Industry",
    icon: "🏭",
    blurb:
      "The sector where import-substitution analysis is sharpest: customs data tells you precisely what a country buys abroad and does not build.",
    supplyIndicator: "NV.IND.MANF.ZS",
    gdpShareBaseline: 0.14,
    segments: [
      {
        id: "mfg-packaging",
        name: "Packaging & Containers",
        description:
          "Cartons, plastics, glass and closures — demand scales with every other manufacturer in the country.",
        hsCodes: ["3923", "4819", "7010", "7612"],
        capitalIntensity: 0.65,
        regulatoryBurden: 0.35,
        infrastructureDependency: 0.8,
        importSubstitutability: 0.9,
        timeToRevenueMonths: 14,
        laborIntensity: 0.4,
        incomeElasticity: 0.6,
        b2b: true,
      },
      {
        id: "mfg-buildingmaterials",
        name: "Building Materials",
        description:
          "Cement products, tiles, aggregates, fittings and finishing materials.",
        hsCodes: ["25", "68", "69", "7308"],
        capitalIntensity: 0.75,
        regulatoryBurden: 0.45,
        infrastructureDependency: 0.85,
        importSubstitutability: 0.85,
        timeToRevenueMonths: 18,
        laborIntensity: 0.5,
        incomeElasticity: 1.2,
        b2b: true,
      },
      {
        id: "mfg-chemicals",
        name: "Chemicals & Cleaning Products",
        description:
          "Detergents, industrial chemicals and household cleaning formulation.",
        hsCodes: ["34", "28", "29"],
        capitalIntensity: 0.6,
        regulatoryBurden: 0.7,
        infrastructureDependency: 0.7,
        importSubstitutability: 0.75,
        timeToRevenueMonths: 14,
        laborIntensity: 0.35,
        incomeElasticity: 0.5,
        b2b: true,
      },
      {
        id: "mfg-metal",
        name: "Metal Fabrication",
        description:
          "Structural steel, sheet metal work, machining and welded assemblies.",
        hsCodes: ["72", "73", "76"],
        capitalIntensity: 0.7,
        regulatoryBurden: 0.4,
        infrastructureDependency: 0.85,
        importSubstitutability: 0.8,
        timeToRevenueMonths: 15,
        laborIntensity: 0.6,
        incomeElasticity: 1.1,
        b2b: true,
      },
      {
        id: "mfg-furniture",
        name: "Furniture & Fittings",
        description:
          "Residential and contract furniture, joinery and fitted interiors.",
        hsCodes: ["94"],
        capitalIntensity: 0.45,
        regulatoryBurden: 0.25,
        infrastructureDependency: 0.6,
        importSubstitutability: 0.9,
        timeToRevenueMonths: 9,
        laborIntensity: 0.75,
        incomeElasticity: 1.3,
        b2b: false,
      },
      {
        id: "mfg-electronics-assembly",
        name: "Electronics Assembly",
        description:
          "Board-level assembly, enclosures and light electronics manufacturing.",
        hsCodes: ["85"],
        capitalIntensity: 0.8,
        regulatoryBurden: 0.5,
        infrastructureDependency: 0.9,
        importSubstitutability: 0.45,
        timeToRevenueMonths: 20,
        laborIntensity: 0.55,
        incomeElasticity: 1.2,
        b2b: true,
      },
      {
        id: "mfg-pharma",
        name: "Generic Pharmaceuticals",
        description:
          "Off-patent drug formulation and packaging for domestic and regional supply.",
        hsCodes: ["30"],
        capitalIntensity: 0.9,
        regulatoryBurden: 0.95,
        infrastructureDependency: 0.9,
        importSubstitutability: 0.55,
        timeToRevenueMonths: 30,
        laborIntensity: 0.4,
        incomeElasticity: 0.4,
        b2b: true,
      },
    ],
  },
  {
    id: "realestate",
    name: "Real Estate & Construction",
    icon: "🏗️",
    blurb:
      "Driven by demography and urbanisation rather than trade. The engine reads household formation against housing stock and urban migration.",
    supplyIndicator: "NV.IND.TOTL.ZS",
    gdpShareBaseline: 0.13,
    segments: [
      {
        id: "re-affordable-housing",
        name: "Affordable & Mid-Market Housing",
        description:
          "Volume residential development aimed at median household income, not luxury.",
        hsCodes: [],
        capitalIntensity: 0.95,
        regulatoryBurden: 0.8,
        infrastructureDependency: 0.85,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 30,
        laborIntensity: 0.7,
        incomeElasticity: 0.9,
        b2b: false,
      },
      {
        id: "re-rental-management",
        name: "Rental & Property Management",
        description:
          "Operating and managing rental stock on behalf of owners — asset-light versus development.",
        hsCodes: [],
        capitalIntensity: 0.2,
        regulatoryBurden: 0.4,
        infrastructureDependency: 0.3,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 4,
        laborIntensity: 0.6,
        incomeElasticity: 0.9,
        b2b: false,
      },
      {
        id: "re-proptech",
        name: "PropTech & Listings",
        description:
          "Search, transaction, valuation and management software for property markets.",
        hsCodes: [],
        capitalIntensity: 0.2,
        regulatoryBurden: 0.2,
        infrastructureDependency: 0.3,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 10,
        laborIntensity: 0.4,
        incomeElasticity: 1.2,
        b2b: true,
      },
      {
        id: "re-retrofit",
        name: "Retrofit & Energy Efficiency",
        description:
          "Upgrading existing building stock for insulation, solar and self-generation.",
        hsCodes: ["8541", "7308"],
        capitalIntensity: 0.4,
        regulatoryBurden: 0.4,
        infrastructureDependency: 0.5,
        importSubstitutability: 0.9,
        timeToRevenueMonths: 7,
        laborIntensity: 0.8,
        incomeElasticity: 1.0,
        b2b: false,
      },
      {
        id: "re-contracting",
        name: "Specialised Contracting",
        description:
          "MEP, finishing and technical trades subcontracted to larger developments.",
        hsCodes: [],
        capitalIntensity: 0.35,
        regulatoryBurden: 0.45,
        infrastructureDependency: 0.5,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 6,
        laborIntensity: 0.9,
        incomeElasticity: 1.2,
        b2b: true,
      },
    ],
  },
  {
    id: "energy",
    name: "Energy & Utilities",
    icon: "⚡",
    blurb:
      "Where grid reliability is poor, private generation and storage stop being a green choice and become basic infrastructure demand.",
    supplyIndicator: "EG.USE.ELEC.KH.PC",
    gdpShareBaseline: 0.05,
    segments: [
      {
        id: "energy-solar",
        name: "Solar PV & Installation",
        description:
          "Residential and commercial photovoltaic supply, installation and maintenance.",
        hsCodes: ["8541"],
        capitalIntensity: 0.45,
        regulatoryBurden: 0.4,
        infrastructureDependency: 0.35,
        importSubstitutability: 0.7,
        timeToRevenueMonths: 6,
        laborIntensity: 0.7,
        incomeElasticity: 1.0,
        b2b: false,
      },
      {
        id: "energy-storage",
        name: "Battery Storage & Backup",
        description:
          "Storage systems, inverters and backup power for unreliable grids.",
        hsCodes: ["8507", "8504"],
        capitalIntensity: 0.5,
        regulatoryBurden: 0.35,
        infrastructureDependency: 0.4,
        importSubstitutability: 0.5,
        timeToRevenueMonths: 7,
        laborIntensity: 0.55,
        incomeElasticity: 1.0,
        b2b: false,
      },
      {
        id: "energy-water",
        name: "Water Treatment & Supply",
        description:
          "Purification, desalination, bottling and private water distribution.",
        hsCodes: ["8421"],
        capitalIntensity: 0.65,
        regulatoryBurden: 0.6,
        infrastructureDependency: 0.7,
        importSubstitutability: 0.75,
        timeToRevenueMonths: 12,
        laborIntensity: 0.5,
        incomeElasticity: 0.5,
        b2b: false,
      },
      {
        id: "energy-efficiency-services",
        name: "Energy Services & Metering",
        description:
          "Monitoring, submetering and managed energy contracts for buildings and industry.",
        hsCodes: ["9028", "9030"],
        capitalIntensity: 0.35,
        regulatoryBurden: 0.45,
        infrastructureDependency: 0.45,
        importSubstitutability: 0.8,
        timeToRevenueMonths: 9,
        laborIntensity: 0.5,
        incomeElasticity: 0.9,
        b2b: true,
      },
    ],
  },
  {
    id: "healthcare",
    name: "Healthcare & Life Sciences",
    icon: "🩺",
    blurb:
      "Demand is demographic and inelastic. Supply constraints show up as provider density and outbound medical travel.",
    supplyIndicator: "SH.XPD.CHEX.GD.ZS",
    gdpShareBaseline: 0.08,
    segments: [
      {
        id: "health-clinics",
        name: "Outpatient Clinics & Diagnostics",
        description:
          "Primary care, imaging and laboratory services outside the hospital system.",
        hsCodes: [],
        capitalIntensity: 0.55,
        regulatoryBurden: 0.85,
        infrastructureDependency: 0.65,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 12,
        laborIntensity: 0.8,
        incomeElasticity: 0.6,
        b2b: false,
      },
      {
        id: "health-medtech-distribution",
        name: "Medical Devices & Consumables",
        description:
          "Import, distribution and servicing of devices and single-use consumables.",
        hsCodes: ["9018", "9021", "9022", "3005"],
        capitalIntensity: 0.5,
        regulatoryBurden: 0.8,
        infrastructureDependency: 0.55,
        importSubstitutability: 0.5,
        timeToRevenueMonths: 10,
        laborIntensity: 0.4,
        incomeElasticity: 0.6,
        b2b: true,
      },
      {
        id: "health-eldercare",
        name: "Elder & Long-Term Care",
        description:
          "Residential and at-home care for ageing populations.",
        hsCodes: [],
        capitalIntensity: 0.5,
        regulatoryBurden: 0.75,
        infrastructureDependency: 0.5,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 12,
        laborIntensity: 0.95,
        incomeElasticity: 0.9,
        b2b: false,
      },
      {
        id: "health-digital",
        name: "Digital Health & Telemedicine",
        description:
          "Remote consultation, records, adherence and care-coordination platforms.",
        hsCodes: [],
        capitalIntensity: 0.25,
        regulatoryBurden: 0.6,
        infrastructureDependency: 0.35,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 12,
        laborIntensity: 0.4,
        incomeElasticity: 1.1,
        b2b: true,
      },
      {
        id: "health-pharmacy",
        name: "Pharmacy & Distribution",
        description:
          "Retail pharmacy networks and pharmaceutical wholesale logistics.",
        hsCodes: ["30"],
        capitalIntensity: 0.45,
        regulatoryBurden: 0.85,
        infrastructureDependency: 0.6,
        importSubstitutability: 0.7,
        timeToRevenueMonths: 8,
        laborIntensity: 0.6,
        incomeElasticity: 0.4,
        b2b: false,
      },
    ],
  },
  {
    id: "technology",
    name: "Technology & Software",
    icon: "💻",
    blurb:
      "Largely invisible to customs data, so the engine scores it on connectivity, talent supply, wage arbitrage and services-export capacity.",
    supplyIndicator: "IT.NET.USER.ZS",
    gdpShareBaseline: 0.05,
    segments: [
      {
        id: "tech-saas-vertical",
        name: "Vertical SaaS",
        description:
          "Software built for one industry's workflow rather than general-purpose tooling.",
        hsCodes: [],
        capitalIntensity: 0.2,
        regulatoryBurden: 0.2,
        infrastructureDependency: 0.35,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 12,
        laborIntensity: 0.5,
        incomeElasticity: 1.2,
        b2b: true,
      },
      {
        id: "tech-outsourcing",
        name: "Software Outsourcing & Services",
        description:
          "Engineering capacity sold into higher-wage markets — pure labour arbitrage.",
        hsCodes: [],
        capitalIntensity: 0.15,
        regulatoryBurden: 0.2,
        infrastructureDependency: 0.4,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 4,
        laborIntensity: 0.85,
        incomeElasticity: 1.3,
        b2b: true,
      },
      {
        id: "tech-ai-applications",
        name: "Applied AI Products",
        description:
          "Domain-specific AI tooling layered on foundation models.",
        hsCodes: [],
        capitalIntensity: 0.3,
        regulatoryBurden: 0.3,
        infrastructureDependency: 0.45,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 9,
        laborIntensity: 0.5,
        incomeElasticity: 1.4,
        b2b: true,
      },
      {
        id: "tech-cybersecurity",
        name: "Cybersecurity Services",
        description:
          "Managed detection, compliance and security consulting for regional firms.",
        hsCodes: [],
        capitalIntensity: 0.25,
        regulatoryBurden: 0.35,
        infrastructureDependency: 0.4,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 8,
        laborIntensity: 0.75,
        incomeElasticity: 1.2,
        b2b: true,
      },
      {
        id: "tech-infrastructure",
        name: "Connectivity & Data Infrastructure",
        description:
          "ISPs, colocation, edge capacity and network services.",
        hsCodes: ["8517"],
        capitalIntensity: 0.85,
        regulatoryBurden: 0.75,
        infrastructureDependency: 0.9,
        importSubstitutability: 0.5,
        timeToRevenueMonths: 24,
        laborIntensity: 0.4,
        incomeElasticity: 1.0,
        b2b: true,
      },
    ],
  },
  {
    id: "logistics",
    name: "Logistics & Transportation",
    icon: "🚚",
    blurb:
      "Derived demand: it scales with trade volume and e-commerce penetration rather than with population alone.",
    supplyIndicator: "IS.SHP.GOOD.TU",
    gdpShareBaseline: 0.07,
    segments: [
      {
        id: "log-lastmile",
        name: "Last-Mile Delivery",
        description:
          "Parcel and food delivery into dense urban areas.",
        hsCodes: [],
        capitalIntensity: 0.3,
        regulatoryBurden: 0.35,
        infrastructureDependency: 0.55,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 5,
        laborIntensity: 0.9,
        incomeElasticity: 1.3,
        b2b: true,
      },
      {
        id: "log-warehousing",
        name: "Warehousing & Fulfilment",
        description:
          "Third-party storage, pick-and-pack and inventory services.",
        hsCodes: [],
        capitalIntensity: 0.7,
        regulatoryBurden: 0.35,
        infrastructureDependency: 0.75,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 12,
        laborIntensity: 0.65,
        incomeElasticity: 1.1,
        b2b: true,
      },
      {
        id: "log-coldchain",
        name: "Cold Chain Logistics",
        description:
          "Temperature-controlled transport and storage for food and pharma.",
        hsCodes: ["8418"],
        capitalIntensity: 0.75,
        regulatoryBurden: 0.5,
        infrastructureDependency: 0.9,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 14,
        laborIntensity: 0.5,
        incomeElasticity: 0.9,
        b2b: true,
      },
      {
        id: "log-freight-brokerage",
        name: "Freight Forwarding & Customs",
        description:
          "Brokerage, clearance and documentation for importers and exporters.",
        hsCodes: [],
        capitalIntensity: 0.2,
        regulatoryBurden: 0.6,
        infrastructureDependency: 0.45,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 5,
        laborIntensity: 0.7,
        incomeElasticity: 1.0,
        b2b: true,
      },
    ],
  },
  {
    id: "retail",
    name: "Retail & E-commerce",
    icon: "🛒",
    blurb:
      "Scored on consumer spending power against retail formalisation and internet penetration.",
    supplyIndicator: "IT.NET.USER.ZS",
    gdpShareBaseline: 0.1,
    segments: [
      {
        id: "retail-ecommerce",
        name: "E-commerce Platforms",
        description:
          "Online marketplaces and direct-to-consumer retail operations.",
        hsCodes: [],
        capitalIntensity: 0.3,
        regulatoryBurden: 0.3,
        infrastructureDependency: 0.55,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 7,
        laborIntensity: 0.5,
        incomeElasticity: 1.3,
        b2b: false,
      },
      {
        id: "retail-grocery",
        name: "Grocery & Convenience",
        description:
          "Food retail formats from neighbourhood convenience to full supermarket.",
        hsCodes: [],
        capitalIntensity: 0.55,
        regulatoryBurden: 0.4,
        infrastructureDependency: 0.65,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 8,
        laborIntensity: 0.75,
        incomeElasticity: 0.7,
        b2b: false,
      },
      {
        id: "retail-b2b-distribution",
        name: "B2B Distribution",
        description:
          "Wholesale supply into retailers, restaurants and industrial buyers.",
        hsCodes: [],
        capitalIntensity: 0.45,
        regulatoryBurden: 0.3,
        infrastructureDependency: 0.6,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 6,
        laborIntensity: 0.55,
        incomeElasticity: 0.9,
        b2b: true,
      },
      {
        id: "retail-resale",
        name: "Resale & Refurbished Goods",
        description:
          "Secondary-market trade in electronics, apparel and durables — counter-cyclical.",
        hsCodes: ["6309"],
        capitalIntensity: 0.25,
        regulatoryBurden: 0.25,
        infrastructureDependency: 0.4,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 4,
        laborIntensity: 0.7,
        incomeElasticity: 0.5,
        b2b: false,
      },
    ],
  },
  {
    id: "finance",
    name: "Financial Services & Fintech",
    icon: "🏦",
    blurb:
      "Opportunity concentrates where banking penetration is low but mobile penetration is high — the classic leapfrog gap.",
    supplyIndicator: "FX.OWN.TOTL.ZS",
    gdpShareBaseline: 0.07,
    segments: [
      {
        id: "fin-payments",
        name: "Payments & Wallets",
        description:
          "Digital payment rails, merchant acquiring and consumer wallets.",
        hsCodes: [],
        capitalIntensity: 0.4,
        regulatoryBurden: 0.9,
        infrastructureDependency: 0.5,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 15,
        laborIntensity: 0.4,
        incomeElasticity: 1.1,
        b2b: true,
      },
      {
        id: "fin-sme-lending",
        name: "SME Lending & Working Capital",
        description:
          "Credit for small businesses underserved by incumbent banks.",
        hsCodes: [],
        capitalIntensity: 0.7,
        regulatoryBurden: 0.9,
        infrastructureDependency: 0.4,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 18,
        laborIntensity: 0.45,
        incomeElasticity: 1.0,
        b2b: true,
      },
      {
        id: "fin-remittance",
        name: "Remittances & Cross-Border",
        description:
          "Diaspora transfer corridors and FX services.",
        hsCodes: [],
        capitalIntensity: 0.45,
        regulatoryBurden: 0.9,
        infrastructureDependency: 0.45,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 15,
        laborIntensity: 0.45,
        incomeElasticity: 0.8,
        b2b: false,
      },
      {
        id: "fin-insurance",
        name: "Insurance & Insurtech",
        description:
          "Underwriting and distribution of consumer and commercial cover.",
        hsCodes: [],
        capitalIntensity: 0.6,
        regulatoryBurden: 0.9,
        infrastructureDependency: 0.4,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 20,
        laborIntensity: 0.5,
        incomeElasticity: 1.1,
        b2b: false,
      },
    ],
  },
  {
    id: "education",
    name: "Education & Training",
    icon: "🎓",
    blurb:
      "Scored against youth share of population and the gap between graduate supply and employer demand.",
    supplyIndicator: "SE.XPD.TOTL.GD.ZS",
    gdpShareBaseline: 0.05,
    segments: [
      {
        id: "edu-vocational",
        name: "Vocational & Technical Training",
        description:
          "Trade skills with direct employment outcomes — welding, electrical, technical.",
        hsCodes: [],
        capitalIntensity: 0.4,
        regulatoryBurden: 0.55,
        infrastructureDependency: 0.5,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 8,
        laborIntensity: 0.8,
        incomeElasticity: 0.9,
        b2b: false,
      },
      {
        id: "edu-k12-private",
        name: "Private K-12",
        description:
          "Fee-paying schooling where public provision is weak or oversubscribed.",
        hsCodes: [],
        capitalIntensity: 0.7,
        regulatoryBurden: 0.75,
        infrastructureDependency: 0.6,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 24,
        laborIntensity: 0.9,
        incomeElasticity: 1.2,
        b2b: false,
      },
      {
        id: "edu-edtech",
        name: "EdTech Platforms",
        description:
          "Online learning, tutoring marketplaces and assessment tooling.",
        hsCodes: [],
        capitalIntensity: 0.25,
        regulatoryBurden: 0.25,
        infrastructureDependency: 0.4,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 10,
        laborIntensity: 0.5,
        incomeElasticity: 1.2,
        b2b: false,
      },
      {
        id: "edu-corporate",
        name: "Corporate & Professional Training",
        description:
          "Upskilling sold to employers rather than individuals.",
        hsCodes: [],
        capitalIntensity: 0.2,
        regulatoryBurden: 0.2,
        infrastructureDependency: 0.35,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 5,
        laborIntensity: 0.8,
        incomeElasticity: 1.3,
        b2b: true,
      },
    ],
  },
  {
    id: "tourism",
    name: "Tourism & Hospitality",
    icon: "🧳",
    blurb:
      "Driven by inbound arrivals and receipts. Highly sensitive to security and currency conditions, which the engine treats as risk.",
    supplyIndicator: "ST.INT.ARVL",
    gdpShareBaseline: 0.06,
    segments: [
      {
        id: "tour-boutique-lodging",
        name: "Boutique & Alternative Lodging",
        description:
          "Small-format hotels, guesthouses and managed short-term rentals.",
        hsCodes: [],
        capitalIntensity: 0.7,
        regulatoryBurden: 0.5,
        infrastructureDependency: 0.6,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 16,
        laborIntensity: 0.8,
        incomeElasticity: 1.6,
        b2b: false,
      },
      {
        id: "tour-experiences",
        name: "Tours & Experiences",
        description:
          "Curated activity operators — asset-light and quick to launch.",
        hsCodes: [],
        capitalIntensity: 0.15,
        regulatoryBurden: 0.35,
        infrastructureDependency: 0.35,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 3,
        laborIntensity: 0.85,
        incomeElasticity: 1.7,
        b2b: false,
      },
      {
        id: "tour-medical",
        name: "Medical & Wellness Tourism",
        description:
          "Inbound patients seeking cost or quality arbitrage on procedures.",
        hsCodes: [],
        capitalIntensity: 0.6,
        regulatoryBurden: 0.8,
        infrastructureDependency: 0.65,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 14,
        laborIntensity: 0.75,
        incomeElasticity: 1.3,
        b2b: false,
      },
      {
        id: "tour-diaspora",
        name: "Diaspora & Heritage Travel",
        description:
          "Travel demand from emigrant communities returning seasonally.",
        hsCodes: [],
        capitalIntensity: 0.25,
        regulatoryBurden: 0.3,
        infrastructureDependency: 0.4,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 5,
        laborIntensity: 0.7,
        incomeElasticity: 1.2,
        b2b: false,
      },
    ],
  },
  {
    id: "textiles",
    name: "Textiles & Apparel",
    icon: "🧵",
    blurb:
      "A reliable early-industrialisation sector: low capital thresholds and deep customs data make gaps easy to quantify.",
    supplyIndicator: "NV.IND.MANF.ZS",
    gdpShareBaseline: 0.03,
    segments: [
      {
        id: "tex-apparel-manufacturing",
        name: "Apparel Manufacturing",
        description:
          "Cut-make-trim production for domestic brands or export contracts.",
        hsCodes: ["61", "62"],
        capitalIntensity: 0.45,
        regulatoryBurden: 0.35,
        infrastructureDependency: 0.65,
        importSubstitutability: 0.8,
        timeToRevenueMonths: 10,
        laborIntensity: 0.9,
        incomeElasticity: 1.1,
        b2b: true,
      },
      {
        id: "tex-technical",
        name: "Technical & Industrial Textiles",
        description:
          "Non-fashion textiles: filtration, medical, agricultural and packaging fabrics.",
        hsCodes: ["56", "59"],
        capitalIntensity: 0.65,
        regulatoryBurden: 0.45,
        infrastructureDependency: 0.75,
        importSubstitutability: 0.65,
        timeToRevenueMonths: 16,
        laborIntensity: 0.5,
        incomeElasticity: 0.8,
        b2b: true,
      },
      {
        id: "tex-brands",
        name: "Apparel Brands & Retail",
        description:
          "Own-label clothing brands selling direct to consumers.",
        hsCodes: ["61", "62"],
        capitalIntensity: 0.3,
        regulatoryBurden: 0.2,
        infrastructureDependency: 0.4,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 6,
        laborIntensity: 0.6,
        incomeElasticity: 1.5,
        b2b: false,
      },
      {
        id: "tex-leather",
        name: "Leather & Footwear",
        description:
          "Tanning, leather goods and footwear production.",
        hsCodes: ["41", "42", "64"],
        capitalIntensity: 0.5,
        regulatoryBurden: 0.55,
        infrastructureDependency: 0.7,
        importSubstitutability: 0.75,
        timeToRevenueMonths: 12,
        laborIntensity: 0.85,
        incomeElasticity: 1.3,
        b2b: true,
      },
    ],
  },
  {
    id: "waste",
    name: "Waste & Environment",
    icon: "♻️",
    blurb:
      "Where municipal services have failed, waste becomes a private-sector opportunity with a captive, non-discretionary customer base.",
    supplyIndicator: null,
    gdpShareBaseline: 0.02,
    segments: [
      {
        id: "waste-recycling",
        name: "Recycling & Material Recovery",
        description:
          "Collection, sorting and resale of plastics, paper, metal and glass.",
        hsCodes: ["3915", "4707", "7204", "7001"],
        capitalIntensity: 0.55,
        regulatoryBurden: 0.5,
        infrastructureDependency: 0.7,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 12,
        laborIntensity: 0.75,
        incomeElasticity: 0.6,
        b2b: true,
      },
      {
        id: "waste-collection",
        name: "Waste Collection & Handling",
        description:
          "Commercial and residential collection contracts.",
        hsCodes: [],
        capitalIntensity: 0.6,
        regulatoryBurden: 0.65,
        infrastructureDependency: 0.65,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 10,
        laborIntensity: 0.85,
        incomeElasticity: 0.4,
        b2b: true,
      },
      {
        id: "waste-organic",
        name: "Organic Waste & Composting",
        description:
          "Diverting food and agricultural waste into compost or biogas.",
        hsCodes: ["3101"],
        capitalIntensity: 0.5,
        regulatoryBurden: 0.45,
        infrastructureDependency: 0.6,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 12,
        laborIntensity: 0.65,
        incomeElasticity: 0.5,
        b2b: true,
      },
      {
        id: "waste-water-treatment",
        name: "Wastewater Treatment",
        description:
          "Industrial and municipal effluent treatment and reuse.",
        hsCodes: ["8421"],
        capitalIntensity: 0.8,
        regulatoryBurden: 0.7,
        infrastructureDependency: 0.8,
        importSubstitutability: 0.8,
        timeToRevenueMonths: 20,
        laborIntensity: 0.45,
        incomeElasticity: 0.4,
        b2b: true,
      },
    ],
  },
  {
    id: "mobility",
    name: "Automotive & Mobility",
    icon: "🚗",
    blurb:
      "Vehicle fleets age where new-car affordability collapses, shifting value from sales to maintenance, parts and shared mobility.",
    supplyIndicator: null,
    gdpShareBaseline: 0.04,
    segments: [
      {
        id: "mob-parts-service",
        name: "Parts & Aftermarket Service",
        description:
          "Spares, maintenance and repair for an ageing vehicle fleet.",
        hsCodes: ["8708", "4011"],
        capitalIntensity: 0.4,
        regulatoryBurden: 0.3,
        infrastructureDependency: 0.5,
        importSubstitutability: 0.6,
        timeToRevenueMonths: 6,
        laborIntensity: 0.8,
        incomeElasticity: 0.6,
        b2b: false,
      },
      {
        id: "mob-ev",
        name: "EV & Charging Infrastructure",
        description:
          "Electric vehicle import, conversion and charging networks.",
        hsCodes: ["8703", "8504"],
        capitalIntensity: 0.7,
        regulatoryBurden: 0.55,
        infrastructureDependency: 0.85,
        importSubstitutability: 0.4,
        timeToRevenueMonths: 18,
        laborIntensity: 0.45,
        incomeElasticity: 1.5,
        b2b: false,
      },
      {
        id: "mob-shared",
        name: "Shared & Micro-Mobility",
        description:
          "Ride-hailing, car sharing and two-wheeler fleets.",
        hsCodes: ["8711"],
        capitalIntensity: 0.5,
        regulatoryBurden: 0.6,
        infrastructureDependency: 0.55,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 9,
        laborIntensity: 0.7,
        incomeElasticity: 1.2,
        b2b: false,
      },
      {
        id: "mob-fleet-logistics",
        name: "Fleet Management",
        description:
          "Telematics, leasing and managed fleets for commercial operators.",
        hsCodes: [],
        capitalIntensity: 0.55,
        regulatoryBurden: 0.35,
        infrastructureDependency: 0.5,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 10,
        laborIntensity: 0.5,
        incomeElasticity: 1.0,
        b2b: true,
      },
    ],
  },
  {
    id: "services",
    name: "Professional & Business Services",
    icon: "💼",
    blurb:
      "Counter-cyclical in distressed economies: restructuring, compliance and cost-reduction advisory grow when everything else contracts.",
    supplyIndicator: null,
    gdpShareBaseline: 0.06,
    segments: [
      {
        id: "svc-accounting-compliance",
        name: "Accounting & Compliance",
        description:
          "Bookkeeping, audit support and regulatory filing for SMEs.",
        hsCodes: [],
        capitalIntensity: 0.1,
        regulatoryBurden: 0.5,
        infrastructureDependency: 0.25,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 3,
        laborIntensity: 0.85,
        incomeElasticity: 0.8,
        b2b: true,
      },
      {
        id: "svc-outsourced-ops",
        name: "Outsourced Operations & BPO",
        description:
          "Support, back-office and process work delivered for foreign clients.",
        hsCodes: [],
        capitalIntensity: 0.25,
        regulatoryBurden: 0.25,
        infrastructureDependency: 0.5,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 6,
        laborIntensity: 0.9,
        incomeElasticity: 1.2,
        b2b: true,
      },
      {
        id: "svc-marketing",
        name: "Marketing & Creative Services",
        description:
          "Agencies and studios serving domestic and export clients.",
        hsCodes: [],
        capitalIntensity: 0.12,
        regulatoryBurden: 0.15,
        infrastructureDependency: 0.3,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 3,
        laborIntensity: 0.85,
        incomeElasticity: 1.4,
        b2b: true,
      },
      {
        id: "svc-legal-advisory",
        name: "Legal & Restructuring Advisory",
        description:
          "Corporate, debt and cross-border advisory work.",
        hsCodes: [],
        capitalIntensity: 0.12,
        regulatoryBurden: 0.7,
        infrastructureDependency: 0.25,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 4,
        laborIntensity: 0.9,
        incomeElasticity: 1.0,
        b2b: true,
      },
    ],
  },
  {
    id: "aerospace",
    name: "Aerospace & Drones",
    icon: "🛩️",
    blurb:
      "Airframes and payloads move under customs codes, so the hardware here is measured. Flight operations are not, and are scored on demand and airspace regulation instead.",
    supplyIndicator: "NV.IND.MANF.ZS",
    gdpShareBaseline: 0.012,
    segments: [
      {
        id: "uav-assembly",
        name: "Drone Assembly & Integration",
        description:
          "Airframe build and integration of flight controllers, motors and payloads.",
        hsCodes: ["8806"],
        capitalIntensity: 0.62,
        // Airspace certification is the gate, not the workshop.
        regulatoryBurden: 0.78,
        infrastructureDependency: 0.55,
        importSubstitutability: 0.55,
        timeToRevenueMonths: 18,
        laborIntensity: 0.5,
        incomeElasticity: 1.5,
        b2b: true,
      },
      {
        id: "uav-components",
        name: "Drone Components & Payloads",
        description:
          "Propulsion, ground control, gimbals, cameras and sensing payloads.",
        hsCodes: ["8807", "8525", "9013"],
        capitalIntensity: 0.52,
        regulatoryBurden: 0.45,
        infrastructureDependency: 0.6,
        importSubstitutability: 0.45,
        timeToRevenueMonths: 15,
        laborIntensity: 0.5,
        incomeElasticity: 1.4,
        b2b: true,
      },
      {
        id: "uav-services",
        name: "Drone Survey & Spray Services",
        description:
          "Aerial survey, inspection, mapping and agricultural spraying as a service.",
        hsCodes: [],
        capitalIntensity: 0.22,
        regulatoryBurden: 0.7,
        infrastructureDependency: 0.3,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 6,
        laborIntensity: 0.7,
        incomeElasticity: 1.3,
        b2b: true,
      },
    ],
  },
  {
    id: "defence",
    name: "Defence & Security",
    icon: "🛡️",
    blurb:
      "Measured from published UN trade statistics. Scored with heavy regulatory weight, because licensing and export control bind harder here than capital does — a gap can be real and still be closed to you.",
    supplyIndicator: "NV.IND.MANF.ZS",
    gdpShareBaseline: 0.018,
    segments: [
      {
        id: "def-munitions",
        name: "Small Arms & Ammunition",
        description:
          "Licensed manufacture of small arms, ammunition and their components.",
        hsCodes: ["93"],
        capitalIntensity: 0.82,
        // End-use certificates, national licensing, export control.
        regulatoryBurden: 0.95,
        infrastructureDependency: 0.75,
        importSubstitutability: 0.4,
        timeToRevenueMonths: 30,
        laborIntensity: 0.5,
        incomeElasticity: 0.9,
        b2b: true,
      },
      {
        id: "def-vehicles",
        name: "Armoured & Tactical Vehicles",
        description:
          "Armouring, up-fitting and assembly of protected and tactical vehicles.",
        hsCodes: ["8710"],
        capitalIntensity: 0.8,
        regulatoryBurden: 0.88,
        infrastructureDependency: 0.78,
        importSubstitutability: 0.42,
        timeToRevenueMonths: 28,
        laborIntensity: 0.6,
        incomeElasticity: 0.9,
        b2b: true,
      },
      {
        id: "def-surveillance",
        name: "Surveillance, Radar & Optics",
        description:
          "Radar, night vision, thermal imaging and perimeter detection systems.",
        hsCodes: ["8526", "9013", "8525"],
        capitalIntensity: 0.6,
        regulatoryBurden: 0.82,
        infrastructureDependency: 0.6,
        importSubstitutability: 0.45,
        timeToRevenueMonths: 20,
        laborIntensity: 0.45,
        incomeElasticity: 1.1,
        b2b: true,
      },
      {
        id: "def-protective",
        name: "Protective & Tactical Equipment",
        description:
          "Body armour, helmets and protective gear for defence and civil security.",
        hsCodes: ["6506", "6307"],
        // The lowest barrier in the sector: sewn and moulded goods, not systems.
        capitalIntensity: 0.42,
        regulatoryBurden: 0.65,
        infrastructureDependency: 0.4,
        importSubstitutability: 0.7,
        timeToRevenueMonths: 12,
        laborIntensity: 0.75,
        incomeElasticity: 0.9,
        b2b: true,
      },
    ],
  },
  {
    id: "semiconductors",
    name: "Semiconductors & Advanced Electronics",
    icon: "🔬",
    blurb:
      "Carved out of the broad electronics chapter so chips, fab equipment and power components are ranked on their own terms rather than averaged into board assembly.",
    supplyIndicator: "NV.IND.MANF.ZS",
    gdpShareBaseline: 0.025,
    segments: [
      {
        id: "semi-ic",
        name: "Integrated Circuits & Chips",
        description:
          "Fabrication, packaging and test of integrated circuits.",
        hsCodes: ["8542"],
        // Fabrication is the least localisable thing in the taxonomy.
        capitalIntensity: 0.95,
        regulatoryBurden: 0.5,
        infrastructureDependency: 0.95,
        importSubstitutability: 0.18,
        timeToRevenueMonths: 36,
        laborIntensity: 0.3,
        incomeElasticity: 1.3,
        b2b: true,
      },
      {
        id: "semi-equipment",
        name: "Semiconductor & PCB Equipment",
        description:
          "Tooling for chip fabrication, board assembly and electronic test.",
        hsCodes: ["8486"],
        capitalIntensity: 0.88,
        regulatoryBurden: 0.45,
        infrastructureDependency: 0.9,
        importSubstitutability: 0.25,
        timeToRevenueMonths: 30,
        laborIntensity: 0.35,
        incomeElasticity: 1.3,
        b2b: true,
      },
      {
        id: "semi-discrete",
        name: "Discrete & Power Components",
        description:
          "Diodes, transistors, capacitors, resistors and power semiconductors.",
        hsCodes: ["8541", "8532", "8533", "8534"],
        capitalIntensity: 0.68,
        regulatoryBurden: 0.38,
        infrastructureDependency: 0.78,
        importSubstitutability: 0.4,
        timeToRevenueMonths: 24,
        laborIntensity: 0.45,
        incomeElasticity: 1.2,
        b2b: true,
      },
    ],
  },
  {
    id: "robotics",
    name: "Robotics & AI Compute",
    icon: "🤖",
    blurb:
      "Splits the physical layer AI runs on — machines, servers, data centres — from the integration work on top of it, which carries no customs footprint and is modelled instead.",
    supplyIndicator: "NV.IND.MANF.ZS",
    gdpShareBaseline: 0.02,
    segments: [
      {
        id: "robo-industrial",
        name: "Industrial Automation & Robotics",
        description:
          "Robotic cells, materials handling and factory control systems.",
        hsCodes: ["8479", "8428", "8537"],
        capitalIntensity: 0.72,
        regulatoryBurden: 0.38,
        infrastructureDependency: 0.8,
        importSubstitutability: 0.42,
        timeToRevenueMonths: 24,
        laborIntensity: 0.4,
        incomeElasticity: 1.4,
        b2b: true,
      },
      {
        id: "robo-compute",
        name: "Servers & Compute Hardware",
        description:
          "Server, storage and accelerator hardware, and their subassemblies.",
        hsCodes: ["8471", "8473"],
        capitalIntensity: 0.58,
        regulatoryBurden: 0.32,
        infrastructureDependency: 0.85,
        importSubstitutability: 0.35,
        timeToRevenueMonths: 18,
        laborIntensity: 0.35,
        incomeElasticity: 1.3,
        b2b: true,
      },
      {
        id: "robo-datacenter",
        name: "Data Centre Build & Operations",
        description:
          "Colocation and compute capacity built and operated locally.",
        hsCodes: [],
        // Power and cooling, not chips, are what decide whether this is possible.
        capitalIntensity: 0.88,
        regulatoryBurden: 0.5,
        infrastructureDependency: 0.95,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 24,
        laborIntensity: 0.4,
        incomeElasticity: 1.4,
        b2b: true,
      },
      {
        id: "robo-ai-integration",
        name: "AI Systems Integration",
        description:
          "Deploying and operating AI systems inside existing businesses.",
        hsCodes: [],
        capitalIntensity: 0.18,
        regulatoryBurden: 0.3,
        infrastructureDependency: 0.5,
        importSubstitutability: 1.0,
        timeToRevenueMonths: 6,
        laborIntensity: 0.7,
        incomeElasticity: 1.5,
        b2b: true,
      },
    ],
  },
];

export const SECTOR_BY_ID = new Map(SECTORS.map((s) => [s.id, s]));

export const ALL_SEGMENTS: Array<{ sector: Sector; segment: Segment }> =
  SECTORS.flatMap((sector) =>
    sector.segments.map((segment) => ({ sector, segment })),
  );
